[package]
name = "timerfd-mio"
version = "0.1.0"
edition = "2024"
authors = ["louisbabeschneider"]
description = "Timerfd implementation for mio using rustix"
license = "MIT"
repository = "https://github.com/louisbabeschneider/timerfd-mio"
readme = "README.md"

[package.metadata]
os_support = "Linux only"

[dependencies]
mio = { version = "1.0.3" , features = ["net", "os-ext"]}
rustix = { version = "1.0.5", features = ["std", "time"] }

